---
sidebar: sidebar 
permalink: use/report-create.html 
keywords: BlueXP migration reports, volume reports 
summary: BlueXP 마이그레이션 보고서 서비스를 사용하면 스토리지 환경에서 파일, 디렉토리, 심볼 링크, 하드 링크, 파일 시스템 트리의 깊이와 폭, 가장 큰 파일 등을 신속하게 식별할 수 있습니다. 
---
= 보고서를 만듭니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
파일 수, 디렉토리의 파일, 심볼 링크, 하드 링크, 가장 큰 파일 크기를 표시하는 볼륨 보고서를 생성할 수 있습니다. 있습니다.

보고서를 생성할 때마다 BlueXP 마이그레이션 보고서 서비스가 경로를 검색하고 데이터를 컴파일합니다. 동일한 보고서 정의를 사용하여 해당 보고서의 여러 인스턴스를 가질 수 있습니다.

BlueXP 마이그레이션 보고서 서비스는 볼륨별로 데이터를 표시합니다.

한 번에 하나의 보고서만 생성할 수 있습니다.

보고서를 PDF 파일로 다운로드할 수도 있습니다.


TIP: 모든 BlueXP 마이그레이션 보고서 작업은 BlueXP 타임라인에 나열되어 있습니다. 타임라인을 보려면 BlueXP * 설정 * > * 타임라인 * 을 선택합니다.

.단계
. BlueXP 왼쪽 탐색 창에서 * 스토리지 * > * 마이그레이션 보고서 * 를 선택합니다.
. 새 보고서 작성 * 을 선택합니다.
. 보고서 이름을 입력합니다.
. 드롭다운 목록에서 작업 환경을 선택합니다.
+
BlueXP에서 활성화되고 활성화된 환경만 작업 환경 목록에 표시됩니다.

+

TIP: BlueXP Connector는 데이터에 액세스하려면 볼륨의 데이터 LIF에 액세스할 수 있어야 합니다.

+
환경을 활성화하려면 을 참조하십시오 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#when-a-connector-is-required["BlueXP 설명서에서 커넥터에 대해 자세히 알아보십시오"].

. 검색 * 아이콘을 사용하여 보고할 볼륨을 검색하거나 목록에서 선택합니다.
. 볼륨을 선택합니다.
. 보고서 작성 * 을 선택합니다.
+
BlueXP 마이그레이션 보고서 서비스는 보고서를 생성하고 보고서 목록에 나열합니다.

. 보고서를 표시하려면 * Actions *... 옵션을 선택하고 * 보고서 보기 * 를 선택합니다.
. 보고서의 PDF 파일을 다운로드하려면 * 작업 *... 옵션을 선택하고 * 보고서 다운로드 * 를 선택합니다.
. 동일한 보고서의 다른 인스턴스를 생성하려면 보고서 행을 선택하고 오른쪽에서 * 보고서 추가 * 를 선택합니다.

